### ISSUE TITLE
proto: bad wiretype for field dht.Message.Value: got wiretype 0, want 2

### ISSUE THREAD

**Issue by derkan** [zillolo/dht#2]
Hi,
When I POST this JSON data
 ```json
{
    "key": "eko",
    "value": "x"
}
```
I got no response on client and on node server type this message is printed to console:
`proto: bad wiretype for field dht.Message.Value: got wiretype 0, want 2`

**Comment by eleksaggr** [comment]
Hello derkan,
I reproduced your error.
You must send your API requests to the `httpHost`, **not** the `serviceHost` as specified in the [https://github.com/zillolo/dht/blob/master/README.md](README).

So starting the node with `node localhost:8888 localhost:9999 --leader` you must send your request to `http://localhost:8888`. Otherwise you will encounter your error.

Regards,
Zillolo
